// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/objectbox/focus_session_entity.dart';
import 'data/objectbox/milestone_entity.dart';
import 'data/objectbox/milestone_log_entity.dart';
import 'data/objectbox/preference_entity.dart';
import 'data/objectbox/project_entity.dart';
import 'data/objectbox/project_log_entity.dart';
import 'data/objectbox/seed_import_log_entity.dart';
import 'data/objectbox/tag_entity.dart';
import 'data/objectbox/task_entity.dart';
import 'data/objectbox/task_log_entity.dart';
import 'data/objectbox/task_template_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6718371266120712975),
    name: 'FocusSessionEntity',
    lastPropertyId: const obx_int.IdUid(10, 5419374884456176699),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4564891485542211049),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2646139083080521258),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 2817348344132131540),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3524468859376424282),
        name: 'taskId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(512, 7193308707394197059),
        relationTarget: 'TaskEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8345652478605398226),
        name: 'startedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 337000380863140005),
        name: 'endedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8920869638700146774),
        name: 'actualMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5075433096074989621),
        name: 'estimateMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 271550656868300562),
        name: 'alarmEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8710944574668453338),
        name: 'transferredToTaskId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(513, 6234928090636866762),
        relationTarget: 'TaskEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5419374884456176699),
        name: 'reflectionNote',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1404431084494550955),
    name: 'MilestoneEntity',
    lastPropertyId: const obx_int.IdUid(16, 4434799841636604595),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4681061601808441694),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 911126764634029130),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 7794927659694247051),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3930289270829899571),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(514, 4421485724006711675),
        relationTarget: 'ProjectEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2061636798677610848),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7521792723241574279),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2889201119243305414),
        name: 'dueAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6038691168033421453),
        name: 'startedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1151699487331974024),
        name: 'endedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 95649244406784328),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7094164969837130579),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5449373390590689767),
        name: 'sortIndex',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 9175511317883020009),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3225765079716127952),
        name: 'templateLockCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1822537848322016325),
        name: 'seedSlug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8286565231840499035),
        name: 'allowInstantComplete',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4434799841636604595),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4741447836746607587),
    name: 'MilestoneLogEntity',
    lastPropertyId: const obx_int.IdUid(8, 4098911019679572245),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1886351826906573181),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4653434142764333639),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 2245012771245731289),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5859359409534848207),
        name: 'milestoneId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(515, 4926237917346134513),
        relationTarget: 'MilestoneEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 437973659925263363),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7845745667408062761),
        name: 'action',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1028914654994077981),
        name: 'previous',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8891524192770853061),
        name: 'next',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4098911019679572245),
        name: 'actor',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1996177496222972938),
    name: 'PreferenceEntity',
    lastPropertyId: const obx_int.IdUid(7, 2182116806571864741),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5901767991045788477),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6230088221438392134),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 323819209058469217),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4456180107663869443),
        name: 'localeCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1245494167219224598),
        name: 'themeModeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1928685608306645820),
        name: 'fontScaleLevel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2161345507423597875),
        name: 'clockTickSoundEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2182116806571864741),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2600690502602196967),
    name: 'ProjectEntity',
    lastPropertyId: const obx_int.IdUid(15, 694394999701972190),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3838936851762573206),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 509480922819643683),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 3063407194219810859),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5572768431760229804),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 900673614467786534),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7348139191554411918),
        name: 'dueAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1206717540347190863),
        name: 'startedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8259566676062733413),
        name: 'endedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2171199273560557515),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2094432137325214943),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8302364146624452573),
        name: 'sortIndex',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8445822026449542192),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 871567003690678280),
        name: 'templateLockCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6645906487920589809),
        name: 'seedSlug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 332028266738788133),
        name: 'allowInstantComplete',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 694394999701972190),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 175951611728368779),
    name: 'ProjectLogEntity',
    lastPropertyId: const obx_int.IdUid(8, 4218352040867339913),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6777817151011735161),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1341881592201290967),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(10, 2966151185714027883),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1308157341724802246),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(516, 6350193723700082934),
        relationTarget: 'ProjectEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2557612517516691251),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1288315030058995265),
        name: 'action',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6748352949046043296),
        name: 'previous',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4988407725449302343),
        name: 'next',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4218352040867339913),
        name: 'actor',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 8366758677835368488),
    name: 'SeedImportLogEntity',
    lastPropertyId: const obx_int.IdUid(4, 3271834532936291906),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1509985919540696968),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1860860416755360462),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(12, 8152779469207408957),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2067671732417145715),
        name: 'version',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3271834532936291906),
        name: 'importedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 6636149666599520103),
    name: 'TagEntity',
    lastPropertyId: const obx_int.IdUid(5, 9020067041736899218),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4992358481383494801),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8686022063036772831),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(13, 9010601206502635265),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1906254375874245290),
        name: 'slug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9105421750129483989),
        name: 'kindIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9020067041736899218),
        name: 'localizedLabelsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 6378683649631047747),
    name: 'TaskEntity',
    lastPropertyId: const obx_int.IdUid(19, 4135690768813535838),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8668692260673414812),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8705444120684552207),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(14, 6786026673409024198),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5418961150333072925),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 709922685600985121),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7778060978053236036),
        name: 'dueAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1862641119453163052),
        name: 'startedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7351578146937334216),
        name: 'endedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4721219605671050940),
        name: 'archivedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8122699203993485520),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3663763526643509616),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2847018182617431053),
        name: 'parentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(518, 7929478020734388158),
        relationTarget: 'TaskEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 818740228810462307),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(517, 4274840753395322627),
        relationTarget: 'ProjectEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4944352188205934399),
        name: 'milestoneId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(519, 8842834517172243327),
        relationTarget: 'MilestoneEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6345703920024940394),
        name: 'sortIndex',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6434005855383926536),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1793577779393911879),
        name: 'templateLockCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 237842594933706196),
        name: 'seedSlug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 6697595966317217152),
        name: 'allowInstantComplete',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 4135690768813535838),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'children',
        srcEntity: 'TaskEntity',
        srcField: 'parent',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 7784018576379429034),
    name: 'TaskLogEntity',
    lastPropertyId: const obx_int.IdUid(8, 7470054406841117698),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7304605759169505855),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 930404537216479826),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(18, 560699089937792394),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 390596859589807562),
        name: 'taskId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(520, 6102551180377507923),
        relationTarget: 'TaskEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6021085917238879854),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7270258383761570300),
        name: 'action',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9097698565378706111),
        name: 'previous',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3504431146081432967),
        name: 'next',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7470054406841117698),
        name: 'actor',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 4029050251438466927),
    name: 'TaskTemplateEntity',
    lastPropertyId: const obx_int.IdUid(10, 8184207848364770612),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1656214579294038797),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1331819069893069955),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(20, 485178767762153002),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6099189394824800439),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1843686885473932177),
        name: 'parentTaskId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(521, 740690952603626189),
        relationTarget: 'TaskEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2192924063091748117),
        name: 'defaultTags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 376873957905556962),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3630037505427994432),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4661323252462084231),
        name: 'lastUsedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2914020907660415871),
        name: 'seedSlug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8184207848364770612),
        name: 'suggestedEstimateMinutes',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(11, 4029050251438466927),
    lastIndexId: const obx_int.IdUid(521, 740690952603626189),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [
      8765915944238401916,
      3848848768755387267,
      2653970785342609710,
      9164101278000633068,
      7379767740225842863,
      3675984080950940919,
      5728852031585476116,
      3292584996523367786,
      6276449398230519495,
      5970291637969587142,
      2107145068344910352,
      833593066153719842,
      735215238262194415,
      409015203332516820,
      1509197506579948700,
      5408939631862680893,
      1009372918984632063,
      7520362425814149801,
      2704772248281868123,
      688667820381873213,
      8803758303169110062,
      2277614760136321164,
      73802065806757889,
      2217707636306848691,
      4386390457749902832,
      4892148018336333220,
      3814516591019267486,
      4015765491204099445,
      2282058664274497904,
      2183876125386301592,
      7619709946800905278,
      5291513772708794816,
      4581070588110497335,
      5699952084521078352,
      7072092060881671554,
      6449749235007046584,
      1219021891474817260,
      5331587738537191911,
      4073333293476657361,
      8382502540712308317,
      1032277044022251544,
      9172371580514816282,
      3236418974711545812,
      242849022916803392,
      7367066274224876792,
      4972726521978112568,
      8795187096480288316,
      5616791797322580036,
      7124646865635612150,
      9016639382424942218,
      6028975752809779069,
      9165706192264873814,
      1062199339814155882,
      5855201554174468451,
      4837806429016214771,
      5803961194149266313,
      8368748859610298658,
      2168399585778410183,
      8958645657050227906,
      5853314043339936527,
      3740537961829380228,
      6484127714656453609,
      1626843833534125442,
      2984689954906703442,
      3665027694905159353,
      5243832177669357422,
      1086390954433235523,
      8601830151944960554,
      3669562853844394738,
      8506669245361872440,
      480728477499871825,
      2664422957955558466,
      615884261067522763,
      4065331184795235012,
      8576641796308036836,
      9098937018580510616,
      833342670011042270,
      34548555192181217,
      483566113866538473,
      2310910826979704190,
      1583784337872069775,
      1455968156251645403,
      2643444677788300193,
      6534148653025395484,
      15486845297609866,
      2690566830561761069,
      92389399641875383,
      6224857608772363956,
      3322443768687390192,
      2433565462048750335,
      6081899948187573944,
      60123079929639074,
      2165413455355081004,
      844552405268694096,
      5154096258779601968,
      5546527216867332282,
      1366538406786852459,
      350121868327985112,
      8884137860015714066,
      4308780398407327169,
      7937095265434947339,
      5184812573743374893,
      8615188194818595801,
      7889741190682919140,
      271365662278366555,
      5483214733082498999,
      5433738285556925965,
      3396654713915819074,
      745362868318060712,
      7249136201952400799,
      102344478750836585,
      4529661969840156356,
      9115344141794374151,
      2719813792460107663,
      1049305491149298741,
      1358672724529529678,
      7532465859218981326,
      214760908436140374,
      2465998140385037036,
      7786977299248508351,
      8522408822698985597,
      7840339522940986048,
      3254685827116109521,
      1394555115547206891,
      2426896795915809260,
      6261560630572878037,
      1251625448497223949,
      1796391387839904317,
      3425578878139107868,
      4205363957135922487,
      8606276618870815474,
      5324989349651626171,
      1608545652968567056,
      7291330500548168976,
      8839409063821176269,
      1192053015482969341,
      2988054282136343392,
      2739670162455301519,
      2532829367697200405,
      8990012559274558832,
      4304027388784932405,
      7782946604505706239,
      8370467393275180229,
      4021633526279751299,
      8099207359445229124,
      7548644677470640013,
      5483954130338504106,
      8548621919230578507,
      1503903002874492594,
      4046251969755789784,
      6067879300447348413,
      7637860772716611168,
      6649469334213107866,
      8057054610419964079,
      2443647535711991180,
      8812221542617935890,
      4901784571725529426,
      902668383995204059,
      6200277537727292672,
      4573715036957954368,
      1143329719290761194,
      3926960127019513053,
      2478880832495559744,
      5033106753130334213,
      7471504033571432782,
      4487452149146235294,
      4095934599404995290,
      4277648396260576327,
      7267790821000413962,
      4580553953119589357,
      1635520581994132870,
      5892005984430609751,
      4732291484325273473,
      6431919305579393886,
      1150960038049659228,
      8590167617220882949,
      5393551983481784506,
      5936036181464007841,
      7836887608607589881,
      823571915825298169,
      5342221038110542455,
      4448843929314153880,
      1358788196869176851,
      5572836092293964295,
      8186602285842160382,
      8663348112367714921,
      8853615691251578417,
      8280434558260555793,
      8788763682293588585,
      3956451088562481360,
      8504922967188063523,
      19736527164843285,
      7992639526881820246,
      3857131573419003183,
      7700913507377465584,
      8427814015572648787,
      3883092328754704517,
      7311595325701391165,
      755719292144196421,
      4467835423040914643,
      7393682796608200402,
      2580191244464287444,
      4816294348887459892,
      1191249965216753083,
      7026339006639247084,
      5632436833416114240,
      2156897494779910545,
      1323918244239450793,
      1978216585356451067,
      2113454388435537793,
      2313784268068396264,
      2369066630145277695,
      8046648158291858588,
      3462538232424282275,
      1928648023392421959,
      4507848000704203635,
      4125183171765719012,
      1685029727310587626,
      1255238273897049143,
      4127144012689345253,
      1733892743117740411,
      8790461550063265362,
      3314353284339928788,
      4351344937250020660,
      1461590642642006953,
      4137071927611383803,
      4544340810908252226,
      6005340853951138459,
      5113513673325495906,
      1092968771286092512,
      7814547923285163969,
      335532067288024386,
      5588100516467433164,
      7014169517503561112,
      7580558768042605758,
      8055057433853511913,
      402545238241182835,
      5287736297938485414,
      1811253888457820773,
      5323107211378975505,
      4831829621901997162,
      836327687845189002,
      4221654704896563745,
      2203363283413789465,
      8738775848292345905,
      8893595623177663550,
      5275005452324339040,
      6089815608636251075,
      1499271457511288058,
      1792306701911160481,
      4858516228478914343,
      9115762703398935956,
      1391081216508932095,
      6923744456231785181,
      5400570158968341730,
      6300706860093538702,
      4000623527701811574,
      7692599491644487766,
      4493965843602895276,
      7765416253680102789,
      3383022253870080435,
      6489017805754423302,
      8347771249685772178,
      7097518871442456011,
      8736378260754538479,
      1001147971066692657,
      5972600616950157274,
      8913270414777529855,
      7246795378660952027,
      114217591311841217,
      2415297491883076263,
      5707905196295151841,
      3977534888048485162,
      1913736480748068487,
      6650118578135849018,
      4585184978286846193,
      8507102094992750924,
      4466872945093440150,
      7331776223902778962,
      1171419914366496252,
      3292278795087310317,
      925119262124431024,
      8832648049125186753,
      5378265330923876929,
      333417025819412445,
      4133164408969617472,
      6646831437584078090,
      8010734479061601798,
      8350039231389843255,
      2127740456934971610,
      6209036080460496089,
      3543263151406831161,
      6559717057602002098,
      2949590742259597072,
      318792597309934079,
      6044980256876730519,
      7430618132704267176,
      65828099318606715,
      8127444965273533635,
      2959950109830574720,
      3311892469097792518,
      616003163780021028,
      5195643685712183269,
      8183352239449240677,
      494891573023030895,
      2299297436320166351,
      809254160179057746,
      7190056751037925738,
      4790868991256733434,
      8999330034851065224,
      8389338312788085171,
      4869503110581418144,
      1390757554426579624,
      127109292779940585,
      6490097704399449287,
      324288137675057469,
      2195986811516645099,
      6185941656496308720,
      2505607984026141846,
      448041520443686981,
      394402150534898535,
      1376988177682058577,
      3652044532646495544,
      3788178543296687263,
      8462696786522406261,
      331741012677261625,
      5732757065076586255,
      1303950741479025068,
      5944092633960526569,
      7380605990200736316,
      2768202334639867070,
      6837223116210960602,
      7614185660225437790,
      8137725463588423903,
      5637979612969317466,
      1349900543901349623,
      5348194550529834877,
      2218878297135660847,
      592240110053327932,
      8391705678874782025,
      3047126319635061081,
      7522285755423464944,
      4418979599654259193,
      344267538491021336,
      401879217468929581,
      2642378027120401256,
      5025071533032056999,
      4916424557925085390,
      8062062655823519325,
      3585114368187622179,
      5193402844300599245,
      8416603703549409801,
      4959800904169429994,
      3947003948230676795,
      2350074982480501503,
      7393339862862190938,
      3605648913999824408,
      7529308220475559288,
      7182379780343546603,
      29306943935747809,
      6096668375444010013,
      6632284942704043612,
      8750193672626594978,
      3925317505159158210,
      3266330269912156796,
      1828114176734313587,
      3332391318154903963,
      9075121001126903140,
      1041008459090236669,
      3382134662817092800,
      1861859253189771404,
      6355425903779851747,
      4389975426007305109,
      7036451678280420982,
      4898721370548373965,
      8907421461261812355,
      7077466693787314263,
      2101065595430834470,
      7965552078403246793,
      5578783463291925592,
      577498196522452447,
      8690344517996855075,
      5115617415842572665,
      5738210571455025413,
      495810395272733706,
      749258897975714820,
      359435660316197136,
      5173311833887853233,
      8032330709269776946,
      597704535353710625,
      8783940451314730893,
      6255603140760812298,
      5186085768414110340,
      2838065228121115791,
      4203177526613260666,
      8883042184264858369,
      8763973852137100126,
      1303101210990542580,
      3662532381673339591,
      3972219992575143891,
      254037558610169249,
      4542908494220166899,
      517639413940778339,
      6088070315927715030,
      6705479839041456289,
      2020881878094884033,
      2147542927352142581,
      3467815756739668824,
      3096679136845353882,
      6629498945238439584,
      7670866036687423790,
      829789989847666756,
      8874404077243070576,
      562156731422658148,
      2145544411553974156,
      3620193378523703613,
      3205393035169741367,
      7900771849755486214,
      8847096466101817291,
      2496546001440089651,
      5740878836898885009,
      6129497925634241399,
      1751307702259422743,
      938775512618549668,
      5797814890335473302,
      1039490527343543888,
      1118053068995875744,
      2135791766470431555,
      2563519230205365927,
      3105550908881024348,
      6354425663899719679,
      6273957413576981018,
      5605046346649588870,
      6899047049597709326,
      7268210386428278971,
      551295601053916723,
      8452188266789351595,
      4955703342639298039,
      7189915064811881574,
      1536007862407431544,
      4108812784627704563,
      3371543595720462860,
      6193430693004612784,
      4178867984899489131,
      4644333389951715448,
      6685122901324730773,
      2733710572389722626,
      8234953931424454949,
      6147501220896008460,
      5436908769220073402,
      3114344301302893661,
      7958990375887187766,
      85351858909024844,
      4824587100068936957,
      9032131748906922590,
      917812814853129873,
      2094838251682481630,
      8101997701200419602,
      1229739431378121866,
      5594590217454117668,
      6335713315206247571,
      5395739512049424135,
      7894554886649587074,
      8893698505626273602,
      5805607248146885742,
      7762705090106183609,
      1417904949027143026,
      2805892518218341089,
      4779778146056443804,
      9169730221819189375,
      6612860313683280163,
      7848282092874872933,
      4745292138937640008,
      1335594734206075657,
      8400151360954901931,
      6833315969332346708,
      3230678694360031444,
      5347685420971009625,
      6399573010619857362,
      2837293229214230492,
      4264117821512598101,
      8350077157369749488,
      6302249016425857209,
      8968072489726540758,
      3469941180210723879,
      8316894334543437278,
      685415504679855252,
      6283662215847861669,
      3446580547824082113,
      4863420929025867434,
      7301863924582081762,
      3255283506662790671,
      7685020435826627866,
      4778136221796448400,
      5943734598653703667,
      835465625289058683,
      2086928756712949608,
      2106690156545694898,
      8065508109555233772,
      2433260137090200359,
    ],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FocusSessionEntity: obx_int.EntityDefinition<FocusSessionEntity>(
      model: _entities[0],
      toOneRelations: (FocusSessionEntity object) => [
        object.task,
        object.transferredToTask,
      ],
      toManyRelations: (FocusSessionEntity object) => {},
      getId: (FocusSessionEntity object) => object.obxId,
      setId: (FocusSessionEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (FocusSessionEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final reflectionNoteOffset = object.reflectionNote == null
            ? null
            : fbb.writeString(object.reflectionNote!);
        fbb.startTable(11);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.task.targetId);
        fbb.addInt64(3, object.startedAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.endedAt?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.actualMinutes);
        fbb.addInt64(6, object.estimateMinutes);
        fbb.addBool(7, object.alarmEnabled);
        fbb.addInt64(8, object.transferredToTask.targetId);
        fbb.addOffset(9, reflectionNoteOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final startedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final endedAtParam = endedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endedAtValue);
        final actualMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final estimateMinutesParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final alarmEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final reflectionNoteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = FocusSessionEntity(
          obxId: obxIdParam,
          id: idParam,
          startedAt: startedAtParam,
          endedAt: endedAtParam,
          actualMinutes: actualMinutesParam,
          estimateMinutes: estimateMinutesParam,
          alarmEnabled: alarmEnabledParam,
          reflectionNote: reflectionNoteParam,
        );
        object.task.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.task.attach(store);
        object.transferredToTask.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.transferredToTask.attach(store);
        return object;
      },
    ),
    MilestoneEntity: obx_int.EntityDefinition<MilestoneEntity>(
      model: _entities[1],
      toOneRelations: (MilestoneEntity object) => [object.project],
      toManyRelations: (MilestoneEntity object) => {},
      getId: (MilestoneEntity object) => object.obxId,
      setId: (MilestoneEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (MilestoneEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final titleOffset = fbb.writeString(object.title);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final seedSlugOffset = object.seedSlug == null
            ? null
            : fbb.writeString(object.seedSlug!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(17);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.project.targetId);
        fbb.addOffset(3, titleOffset);
        fbb.addInt64(4, object.statusIndex);
        fbb.addInt64(5, object.dueAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.startedAt?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.endedAt?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addFloat64(10, object.sortIndex);
        fbb.addOffset(11, tagsOffset);
        fbb.addInt64(12, object.templateLockCount);
        fbb.addOffset(13, seedSlugOffset);
        fbb.addBool(14, object.allowInstantComplete);
        fbb.addOffset(15, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final startedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final endedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final dueAtParam = dueAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueAtValue);
        final startedAtParam = startedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(startedAtValue);
        final endedAtParam = endedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endedAtValue);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final sortIndexParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 26, []);
        final templateLockCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final seedSlugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final allowInstantCompleteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final object = MilestoneEntity(
          obxId: obxIdParam,
          id: idParam,
          title: titleParam,
          statusIndex: statusIndexParam,
          dueAt: dueAtParam,
          startedAt: startedAtParam,
          endedAt: endedAtParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          sortIndex: sortIndexParam,
          tags: tagsParam,
          templateLockCount: templateLockCountParam,
          seedSlug: seedSlugParam,
          allowInstantComplete: allowInstantCompleteParam,
          description: descriptionParam,
        );
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.project.attach(store);
        return object;
      },
    ),
    MilestoneLogEntity: obx_int.EntityDefinition<MilestoneLogEntity>(
      model: _entities[2],
      toOneRelations: (MilestoneLogEntity object) => [object.milestone],
      toManyRelations: (MilestoneLogEntity object) => {},
      getId: (MilestoneLogEntity object) => object.obxId,
      setId: (MilestoneLogEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (MilestoneLogEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final actionOffset = fbb.writeString(object.action);
        final previousOffset = object.previous == null
            ? null
            : fbb.writeString(object.previous!);
        final nextOffset = object.next == null
            ? null
            : fbb.writeString(object.next!);
        final actorOffset = object.actor == null
            ? null
            : fbb.writeString(object.actor!);
        fbb.startTable(9);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.milestone.targetId);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(4, actionOffset);
        fbb.addOffset(5, previousOffset);
        fbb.addOffset(6, nextOffset);
        fbb.addOffset(7, actorOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final actionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final previousParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final nextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final actorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object = MilestoneLogEntity(
          obxId: obxIdParam,
          id: idParam,
          timestamp: timestampParam,
          action: actionParam,
          previous: previousParam,
          next: nextParam,
          actor: actorParam,
        );
        object.milestone.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.milestone.attach(store);
        return object;
      },
    ),
    PreferenceEntity: obx_int.EntityDefinition<PreferenceEntity>(
      model: _entities[3],
      toOneRelations: (PreferenceEntity object) => [],
      toManyRelations: (PreferenceEntity object) => {},
      getId: (PreferenceEntity object) => object.obxId,
      setId: (PreferenceEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (PreferenceEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final localeCodeOffset = fbb.writeString(object.localeCode);
        final fontScaleLevelOffset = fbb.writeString(object.fontScaleLevel);
        fbb.startTable(8);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, localeCodeOffset);
        fbb.addInt64(3, object.themeModeIndex);
        fbb.addOffset(4, fontScaleLevelOffset);
        fbb.addBool(5, object.clockTickSoundEnabled);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final localeCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final themeModeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final fontScaleLevelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final clockTickSoundEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = PreferenceEntity(
          obxId: obxIdParam,
          id: idParam,
          localeCode: localeCodeParam,
          themeModeIndex: themeModeIndexParam,
          fontScaleLevel: fontScaleLevelParam,
          clockTickSoundEnabled: clockTickSoundEnabledParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    ProjectEntity: obx_int.EntityDefinition<ProjectEntity>(
      model: _entities[4],
      toOneRelations: (ProjectEntity object) => [],
      toManyRelations: (ProjectEntity object) => {},
      getId: (ProjectEntity object) => object.obxId,
      setId: (ProjectEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (ProjectEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final titleOffset = fbb.writeString(object.title);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final seedSlugOffset = object.seedSlug == null
            ? null
            : fbb.writeString(object.seedSlug!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(16);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.statusIndex);
        fbb.addInt64(4, object.dueAt?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.startedAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.endedAt?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.addFloat64(9, object.sortIndex);
        fbb.addOffset(10, tagsOffset);
        fbb.addInt64(11, object.templateLockCount);
        fbb.addOffset(12, seedSlugOffset);
        fbb.addBool(13, object.allowInstantComplete);
        fbb.addOffset(14, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final startedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final endedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final dueAtParam = dueAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueAtValue);
        final startedAtParam = startedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(startedAtValue);
        final endedAtParam = endedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endedAtValue);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final sortIndexParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 24, []);
        final templateLockCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final seedSlugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final allowInstantCompleteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final object = ProjectEntity(
          obxId: obxIdParam,
          id: idParam,
          title: titleParam,
          statusIndex: statusIndexParam,
          dueAt: dueAtParam,
          startedAt: startedAtParam,
          endedAt: endedAtParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          sortIndex: sortIndexParam,
          tags: tagsParam,
          templateLockCount: templateLockCountParam,
          seedSlug: seedSlugParam,
          allowInstantComplete: allowInstantCompleteParam,
          description: descriptionParam,
        );

        return object;
      },
    ),
    ProjectLogEntity: obx_int.EntityDefinition<ProjectLogEntity>(
      model: _entities[5],
      toOneRelations: (ProjectLogEntity object) => [object.project],
      toManyRelations: (ProjectLogEntity object) => {},
      getId: (ProjectLogEntity object) => object.obxId,
      setId: (ProjectLogEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (ProjectLogEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final actionOffset = fbb.writeString(object.action);
        final previousOffset = object.previous == null
            ? null
            : fbb.writeString(object.previous!);
        final nextOffset = object.next == null
            ? null
            : fbb.writeString(object.next!);
        final actorOffset = object.actor == null
            ? null
            : fbb.writeString(object.actor!);
        fbb.startTable(9);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.project.targetId);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(4, actionOffset);
        fbb.addOffset(5, previousOffset);
        fbb.addOffset(6, nextOffset);
        fbb.addOffset(7, actorOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final actionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final previousParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final nextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final actorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object = ProjectLogEntity(
          obxId: obxIdParam,
          id: idParam,
          timestamp: timestampParam,
          action: actionParam,
          previous: previousParam,
          next: nextParam,
          actor: actorParam,
        );
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.project.attach(store);
        return object;
      },
    ),
    SeedImportLogEntity: obx_int.EntityDefinition<SeedImportLogEntity>(
      model: _entities[6],
      toOneRelations: (SeedImportLogEntity object) => [],
      toManyRelations: (SeedImportLogEntity object) => {},
      getId: (SeedImportLogEntity object) => object.obxId,
      setId: (SeedImportLogEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (SeedImportLogEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final versionOffset = fbb.writeString(object.version);
        fbb.startTable(5);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, versionOffset);
        fbb.addInt64(3, object.importedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final versionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final importedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = SeedImportLogEntity(
          obxId: obxIdParam,
          id: idParam,
          version: versionParam,
          importedAt: importedAtParam,
        );

        return object;
      },
    ),
    TagEntity: obx_int.EntityDefinition<TagEntity>(
      model: _entities[7],
      toOneRelations: (TagEntity object) => [],
      toManyRelations: (TagEntity object) => {},
      getId: (TagEntity object) => object.obxId,
      setId: (TagEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (TagEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final slugOffset = fbb.writeString(object.slug);
        final localizedLabelsJsonOffset = fbb.writeString(
          object.localizedLabelsJson,
        );
        fbb.startTable(6);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, slugOffset);
        fbb.addInt64(3, object.kindIndex);
        fbb.addOffset(4, localizedLabelsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final slugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final kindIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final localizedLabelsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = TagEntity(
          obxId: obxIdParam,
          id: idParam,
          slug: slugParam,
          kindIndex: kindIndexParam,
          localizedLabelsJson: localizedLabelsJsonParam,
        );

        return object;
      },
    ),
    TaskEntity: obx_int.EntityDefinition<TaskEntity>(
      model: _entities[8],
      toOneRelations: (TaskEntity object) => [
        object.parent,
        object.project,
        object.milestone,
      ],
      toManyRelations: (TaskEntity object) => {
        obx_int.RelInfo<TaskEntity>.toOneBacklink(
          11,
          object.obxId,
          (TaskEntity srcObject) => srcObject.parent,
        ): object.children,
      },
      getId: (TaskEntity object) => object.obxId,
      setId: (TaskEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (TaskEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final titleOffset = fbb.writeString(object.title);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final seedSlugOffset = object.seedSlug == null
            ? null
            : fbb.writeString(object.seedSlug!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(20);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.statusIndex);
        fbb.addInt64(4, object.dueAt?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.startedAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.endedAt?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.archivedAt?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.parent.targetId);
        fbb.addInt64(11, object.project.targetId);
        fbb.addInt64(12, object.milestone.targetId);
        fbb.addFloat64(13, object.sortIndex);
        fbb.addOffset(14, tagsOffset);
        fbb.addInt64(15, object.templateLockCount);
        fbb.addOffset(16, seedSlugOffset);
        fbb.addBool(17, object.allowInstantComplete);
        fbb.addOffset(18, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final startedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final endedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final archivedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final dueAtParam = dueAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueAtValue);
        final startedAtParam = startedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(startedAtValue);
        final endedAtParam = endedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endedAtValue);
        final archivedAtParam = archivedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(archivedAtValue);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final sortIndexParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 32, []);
        final templateLockCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final seedSlugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final allowInstantCompleteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          38,
          false,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final object = TaskEntity(
          obxId: obxIdParam,
          id: idParam,
          title: titleParam,
          statusIndex: statusIndexParam,
          dueAt: dueAtParam,
          startedAt: startedAtParam,
          endedAt: endedAtParam,
          archivedAt: archivedAtParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          sortIndex: sortIndexParam,
          tags: tagsParam,
          templateLockCount: templateLockCountParam,
          seedSlug: seedSlugParam,
          allowInstantComplete: allowInstantCompleteParam,
          description: descriptionParam,
        );
        object.parent.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.parent.attach(store);
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        object.project.attach(store);
        object.milestone.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.milestone.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<TaskEntity>(
          object.children,
          store,
          obx_int.RelInfo<TaskEntity>.toOneBacklink(
            11,
            object.obxId,
            (TaskEntity srcObject) => srcObject.parent,
          ),
        );
        return object;
      },
    ),
    TaskLogEntity: obx_int.EntityDefinition<TaskLogEntity>(
      model: _entities[9],
      toOneRelations: (TaskLogEntity object) => [object.task],
      toManyRelations: (TaskLogEntity object) => {},
      getId: (TaskLogEntity object) => object.obxId,
      setId: (TaskLogEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (TaskLogEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final actionOffset = fbb.writeString(object.action);
        final previousOffset = object.previous == null
            ? null
            : fbb.writeString(object.previous!);
        final nextOffset = object.next == null
            ? null
            : fbb.writeString(object.next!);
        final actorOffset = object.actor == null
            ? null
            : fbb.writeString(object.actor!);
        fbb.startTable(9);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.task.targetId);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(4, actionOffset);
        fbb.addOffset(5, previousOffset);
        fbb.addOffset(6, nextOffset);
        fbb.addOffset(7, actorOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final actionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final previousParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final nextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final actorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object = TaskLogEntity(
          obxId: obxIdParam,
          id: idParam,
          timestamp: timestampParam,
          action: actionParam,
          previous: previousParam,
          next: nextParam,
          actor: actorParam,
        );
        object.task.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.task.attach(store);
        return object;
      },
    ),
    TaskTemplateEntity: obx_int.EntityDefinition<TaskTemplateEntity>(
      model: _entities[10],
      toOneRelations: (TaskTemplateEntity object) => [object.parentTask],
      toManyRelations: (TaskTemplateEntity object) => {},
      getId: (TaskTemplateEntity object) => object.obxId,
      setId: (TaskTemplateEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (TaskTemplateEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final titleOffset = fbb.writeString(object.title);
        final defaultTagsOffset = fbb.writeList(
          object.defaultTags.map(fbb.writeString).toList(growable: false),
        );
        final seedSlugOffset = object.seedSlug == null
            ? null
            : fbb.writeString(object.seedSlug!);
        fbb.startTable(11);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.parentTask.targetId);
        fbb.addOffset(4, defaultTagsOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.lastUsedAt?.millisecondsSinceEpoch);
        fbb.addOffset(8, seedSlugOffset);
        fbb.addInt64(9, object.suggestedEstimateMinutes);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastUsedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final defaultTagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final lastUsedAtParam = lastUsedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastUsedAtValue);
        final seedSlugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final suggestedEstimateMinutesParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 22);
        final object = TaskTemplateEntity(
          obxId: obxIdParam,
          id: idParam,
          title: titleParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          defaultTags: defaultTagsParam,
          lastUsedAt: lastUsedAtParam,
          seedSlug: seedSlugParam,
          suggestedEstimateMinutes: suggestedEstimateMinutesParam,
        );
        object.parentTask.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.parentTask.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FocusSessionEntity] entity fields to define ObjectBox queries.
class FocusSessionEntity_ {
  /// See [FocusSessionEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<FocusSessionEntity>(
    _entities[0].properties[0],
  );

  /// See [FocusSessionEntity.id].
  static final id = obx.QueryStringProperty<FocusSessionEntity>(
    _entities[0].properties[1],
  );

  /// See [FocusSessionEntity.task].
  static final task = obx.QueryRelationToOne<FocusSessionEntity, TaskEntity>(
    _entities[0].properties[2],
  );

  /// See [FocusSessionEntity.startedAt].
  static final startedAt = obx.QueryDateProperty<FocusSessionEntity>(
    _entities[0].properties[3],
  );

  /// See [FocusSessionEntity.endedAt].
  static final endedAt = obx.QueryDateProperty<FocusSessionEntity>(
    _entities[0].properties[4],
  );

  /// See [FocusSessionEntity.actualMinutes].
  static final actualMinutes = obx.QueryIntegerProperty<FocusSessionEntity>(
    _entities[0].properties[5],
  );

  /// See [FocusSessionEntity.estimateMinutes].
  static final estimateMinutes = obx.QueryIntegerProperty<FocusSessionEntity>(
    _entities[0].properties[6],
  );

  /// See [FocusSessionEntity.alarmEnabled].
  static final alarmEnabled = obx.QueryBooleanProperty<FocusSessionEntity>(
    _entities[0].properties[7],
  );

  /// See [FocusSessionEntity.transferredToTask].
  static final transferredToTask =
      obx.QueryRelationToOne<FocusSessionEntity, TaskEntity>(
        _entities[0].properties[8],
      );

  /// See [FocusSessionEntity.reflectionNote].
  static final reflectionNote = obx.QueryStringProperty<FocusSessionEntity>(
    _entities[0].properties[9],
  );
}

/// [MilestoneEntity] entity fields to define ObjectBox queries.
class MilestoneEntity_ {
  /// See [MilestoneEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<MilestoneEntity>(
    _entities[1].properties[0],
  );

  /// See [MilestoneEntity.id].
  static final id = obx.QueryStringProperty<MilestoneEntity>(
    _entities[1].properties[1],
  );

  /// See [MilestoneEntity.project].
  static final project = obx.QueryRelationToOne<MilestoneEntity, ProjectEntity>(
    _entities[1].properties[2],
  );

  /// See [MilestoneEntity.title].
  static final title = obx.QueryStringProperty<MilestoneEntity>(
    _entities[1].properties[3],
  );

  /// See [MilestoneEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<MilestoneEntity>(
    _entities[1].properties[4],
  );

  /// See [MilestoneEntity.dueAt].
  static final dueAt = obx.QueryDateProperty<MilestoneEntity>(
    _entities[1].properties[5],
  );

  /// See [MilestoneEntity.startedAt].
  static final startedAt = obx.QueryDateProperty<MilestoneEntity>(
    _entities[1].properties[6],
  );

  /// See [MilestoneEntity.endedAt].
  static final endedAt = obx.QueryDateProperty<MilestoneEntity>(
    _entities[1].properties[7],
  );

  /// See [MilestoneEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<MilestoneEntity>(
    _entities[1].properties[8],
  );

  /// See [MilestoneEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<MilestoneEntity>(
    _entities[1].properties[9],
  );

  /// See [MilestoneEntity.sortIndex].
  static final sortIndex = obx.QueryDoubleProperty<MilestoneEntity>(
    _entities[1].properties[10],
  );

  /// See [MilestoneEntity.tags].
  static final tags = obx.QueryStringVectorProperty<MilestoneEntity>(
    _entities[1].properties[11],
  );

  /// See [MilestoneEntity.templateLockCount].
  static final templateLockCount = obx.QueryIntegerProperty<MilestoneEntity>(
    _entities[1].properties[12],
  );

  /// See [MilestoneEntity.seedSlug].
  static final seedSlug = obx.QueryStringProperty<MilestoneEntity>(
    _entities[1].properties[13],
  );

  /// See [MilestoneEntity.allowInstantComplete].
  static final allowInstantComplete = obx.QueryBooleanProperty<MilestoneEntity>(
    _entities[1].properties[14],
  );

  /// See [MilestoneEntity.description].
  static final description = obx.QueryStringProperty<MilestoneEntity>(
    _entities[1].properties[15],
  );
}

/// [MilestoneLogEntity] entity fields to define ObjectBox queries.
class MilestoneLogEntity_ {
  /// See [MilestoneLogEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<MilestoneLogEntity>(
    _entities[2].properties[0],
  );

  /// See [MilestoneLogEntity.id].
  static final id = obx.QueryStringProperty<MilestoneLogEntity>(
    _entities[2].properties[1],
  );

  /// See [MilestoneLogEntity.milestone].
  static final milestone =
      obx.QueryRelationToOne<MilestoneLogEntity, MilestoneEntity>(
        _entities[2].properties[2],
      );

  /// See [MilestoneLogEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<MilestoneLogEntity>(
    _entities[2].properties[3],
  );

  /// See [MilestoneLogEntity.action].
  static final action = obx.QueryStringProperty<MilestoneLogEntity>(
    _entities[2].properties[4],
  );

  /// See [MilestoneLogEntity.previous].
  static final previous = obx.QueryStringProperty<MilestoneLogEntity>(
    _entities[2].properties[5],
  );

  /// See [MilestoneLogEntity.next].
  static final next = obx.QueryStringProperty<MilestoneLogEntity>(
    _entities[2].properties[6],
  );

  /// See [MilestoneLogEntity.actor].
  static final actor = obx.QueryStringProperty<MilestoneLogEntity>(
    _entities[2].properties[7],
  );
}

/// [PreferenceEntity] entity fields to define ObjectBox queries.
class PreferenceEntity_ {
  /// See [PreferenceEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[3].properties[0],
  );

  /// See [PreferenceEntity.id].
  static final id = obx.QueryStringProperty<PreferenceEntity>(
    _entities[3].properties[1],
  );

  /// See [PreferenceEntity.localeCode].
  static final localeCode = obx.QueryStringProperty<PreferenceEntity>(
    _entities[3].properties[2],
  );

  /// See [PreferenceEntity.themeModeIndex].
  static final themeModeIndex = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[3].properties[3],
  );

  /// See [PreferenceEntity.fontScaleLevel].
  static final fontScaleLevel = obx.QueryStringProperty<PreferenceEntity>(
    _entities[3].properties[4],
  );

  /// See [PreferenceEntity.clockTickSoundEnabled].
  static final clockTickSoundEnabled =
      obx.QueryBooleanProperty<PreferenceEntity>(_entities[3].properties[5]);

  /// See [PreferenceEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<PreferenceEntity>(
    _entities[3].properties[6],
  );
}

/// [ProjectEntity] entity fields to define ObjectBox queries.
class ProjectEntity_ {
  /// See [ProjectEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<ProjectEntity>(
    _entities[4].properties[0],
  );

  /// See [ProjectEntity.id].
  static final id = obx.QueryStringProperty<ProjectEntity>(
    _entities[4].properties[1],
  );

  /// See [ProjectEntity.title].
  static final title = obx.QueryStringProperty<ProjectEntity>(
    _entities[4].properties[2],
  );

  /// See [ProjectEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<ProjectEntity>(
    _entities[4].properties[3],
  );

  /// See [ProjectEntity.dueAt].
  static final dueAt = obx.QueryDateProperty<ProjectEntity>(
    _entities[4].properties[4],
  );

  /// See [ProjectEntity.startedAt].
  static final startedAt = obx.QueryDateProperty<ProjectEntity>(
    _entities[4].properties[5],
  );

  /// See [ProjectEntity.endedAt].
  static final endedAt = obx.QueryDateProperty<ProjectEntity>(
    _entities[4].properties[6],
  );

  /// See [ProjectEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ProjectEntity>(
    _entities[4].properties[7],
  );

  /// See [ProjectEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ProjectEntity>(
    _entities[4].properties[8],
  );

  /// See [ProjectEntity.sortIndex].
  static final sortIndex = obx.QueryDoubleProperty<ProjectEntity>(
    _entities[4].properties[9],
  );

  /// See [ProjectEntity.tags].
  static final tags = obx.QueryStringVectorProperty<ProjectEntity>(
    _entities[4].properties[10],
  );

  /// See [ProjectEntity.templateLockCount].
  static final templateLockCount = obx.QueryIntegerProperty<ProjectEntity>(
    _entities[4].properties[11],
  );

  /// See [ProjectEntity.seedSlug].
  static final seedSlug = obx.QueryStringProperty<ProjectEntity>(
    _entities[4].properties[12],
  );

  /// See [ProjectEntity.allowInstantComplete].
  static final allowInstantComplete = obx.QueryBooleanProperty<ProjectEntity>(
    _entities[4].properties[13],
  );

  /// See [ProjectEntity.description].
  static final description = obx.QueryStringProperty<ProjectEntity>(
    _entities[4].properties[14],
  );
}

/// [ProjectLogEntity] entity fields to define ObjectBox queries.
class ProjectLogEntity_ {
  /// See [ProjectLogEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<ProjectLogEntity>(
    _entities[5].properties[0],
  );

  /// See [ProjectLogEntity.id].
  static final id = obx.QueryStringProperty<ProjectLogEntity>(
    _entities[5].properties[1],
  );

  /// See [ProjectLogEntity.project].
  static final project =
      obx.QueryRelationToOne<ProjectLogEntity, ProjectEntity>(
        _entities[5].properties[2],
      );

  /// See [ProjectLogEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<ProjectLogEntity>(
    _entities[5].properties[3],
  );

  /// See [ProjectLogEntity.action].
  static final action = obx.QueryStringProperty<ProjectLogEntity>(
    _entities[5].properties[4],
  );

  /// See [ProjectLogEntity.previous].
  static final previous = obx.QueryStringProperty<ProjectLogEntity>(
    _entities[5].properties[5],
  );

  /// See [ProjectLogEntity.next].
  static final next = obx.QueryStringProperty<ProjectLogEntity>(
    _entities[5].properties[6],
  );

  /// See [ProjectLogEntity.actor].
  static final actor = obx.QueryStringProperty<ProjectLogEntity>(
    _entities[5].properties[7],
  );
}

/// [SeedImportLogEntity] entity fields to define ObjectBox queries.
class SeedImportLogEntity_ {
  /// See [SeedImportLogEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<SeedImportLogEntity>(
    _entities[6].properties[0],
  );

  /// See [SeedImportLogEntity.id].
  static final id = obx.QueryStringProperty<SeedImportLogEntity>(
    _entities[6].properties[1],
  );

  /// See [SeedImportLogEntity.version].
  static final version = obx.QueryStringProperty<SeedImportLogEntity>(
    _entities[6].properties[2],
  );

  /// See [SeedImportLogEntity.importedAt].
  static final importedAt = obx.QueryDateProperty<SeedImportLogEntity>(
    _entities[6].properties[3],
  );
}

/// [TagEntity] entity fields to define ObjectBox queries.
class TagEntity_ {
  /// See [TagEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<TagEntity>(
    _entities[7].properties[0],
  );

  /// See [TagEntity.id].
  static final id = obx.QueryStringProperty<TagEntity>(
    _entities[7].properties[1],
  );

  /// See [TagEntity.slug].
  static final slug = obx.QueryStringProperty<TagEntity>(
    _entities[7].properties[2],
  );

  /// See [TagEntity.kindIndex].
  static final kindIndex = obx.QueryIntegerProperty<TagEntity>(
    _entities[7].properties[3],
  );

  /// See [TagEntity.localizedLabelsJson].
  static final localizedLabelsJson = obx.QueryStringProperty<TagEntity>(
    _entities[7].properties[4],
  );
}

/// [TaskEntity] entity fields to define ObjectBox queries.
class TaskEntity_ {
  /// See [TaskEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[0],
  );

  /// See [TaskEntity.id].
  static final id = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[1],
  );

  /// See [TaskEntity.title].
  static final title = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[2],
  );

  /// See [TaskEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[3],
  );

  /// See [TaskEntity.dueAt].
  static final dueAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[4],
  );

  /// See [TaskEntity.startedAt].
  static final startedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[5],
  );

  /// See [TaskEntity.endedAt].
  static final endedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[6],
  );

  /// See [TaskEntity.archivedAt].
  static final archivedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[7],
  );

  /// See [TaskEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[8],
  );

  /// See [TaskEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[8].properties[9],
  );

  /// See [TaskEntity.parent].
  static final parent = obx.QueryRelationToOne<TaskEntity, TaskEntity>(
    _entities[8].properties[10],
  );

  /// See [TaskEntity.project].
  static final project = obx.QueryRelationToOne<TaskEntity, ProjectEntity>(
    _entities[8].properties[11],
  );

  /// See [TaskEntity.milestone].
  static final milestone = obx.QueryRelationToOne<TaskEntity, MilestoneEntity>(
    _entities[8].properties[12],
  );

  /// See [TaskEntity.sortIndex].
  static final sortIndex = obx.QueryDoubleProperty<TaskEntity>(
    _entities[8].properties[13],
  );

  /// See [TaskEntity.tags].
  static final tags = obx.QueryStringVectorProperty<TaskEntity>(
    _entities[8].properties[14],
  );

  /// See [TaskEntity.templateLockCount].
  static final templateLockCount = obx.QueryIntegerProperty<TaskEntity>(
    _entities[8].properties[15],
  );

  /// See [TaskEntity.seedSlug].
  static final seedSlug = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[16],
  );

  /// See [TaskEntity.allowInstantComplete].
  static final allowInstantComplete = obx.QueryBooleanProperty<TaskEntity>(
    _entities[8].properties[17],
  );

  /// See [TaskEntity.description].
  static final description = obx.QueryStringProperty<TaskEntity>(
    _entities[8].properties[18],
  );

  /// see [TaskEntity.children]
  static final children = obx.QueryBacklinkToMany<TaskEntity, TaskEntity>(
    TaskEntity_.parent,
  );
}

/// [TaskLogEntity] entity fields to define ObjectBox queries.
class TaskLogEntity_ {
  /// See [TaskLogEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<TaskLogEntity>(
    _entities[9].properties[0],
  );

  /// See [TaskLogEntity.id].
  static final id = obx.QueryStringProperty<TaskLogEntity>(
    _entities[9].properties[1],
  );

  /// See [TaskLogEntity.task].
  static final task = obx.QueryRelationToOne<TaskLogEntity, TaskEntity>(
    _entities[9].properties[2],
  );

  /// See [TaskLogEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<TaskLogEntity>(
    _entities[9].properties[3],
  );

  /// See [TaskLogEntity.action].
  static final action = obx.QueryStringProperty<TaskLogEntity>(
    _entities[9].properties[4],
  );

  /// See [TaskLogEntity.previous].
  static final previous = obx.QueryStringProperty<TaskLogEntity>(
    _entities[9].properties[5],
  );

  /// See [TaskLogEntity.next].
  static final next = obx.QueryStringProperty<TaskLogEntity>(
    _entities[9].properties[6],
  );

  /// See [TaskLogEntity.actor].
  static final actor = obx.QueryStringProperty<TaskLogEntity>(
    _entities[9].properties[7],
  );
}

/// [TaskTemplateEntity] entity fields to define ObjectBox queries.
class TaskTemplateEntity_ {
  /// See [TaskTemplateEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<TaskTemplateEntity>(
    _entities[10].properties[0],
  );

  /// See [TaskTemplateEntity.id].
  static final id = obx.QueryStringProperty<TaskTemplateEntity>(
    _entities[10].properties[1],
  );

  /// See [TaskTemplateEntity.title].
  static final title = obx.QueryStringProperty<TaskTemplateEntity>(
    _entities[10].properties[2],
  );

  /// See [TaskTemplateEntity.parentTask].
  static final parentTask =
      obx.QueryRelationToOne<TaskTemplateEntity, TaskEntity>(
        _entities[10].properties[3],
      );

  /// See [TaskTemplateEntity.defaultTags].
  static final defaultTags = obx.QueryStringVectorProperty<TaskTemplateEntity>(
    _entities[10].properties[4],
  );

  /// See [TaskTemplateEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TaskTemplateEntity>(
    _entities[10].properties[5],
  );

  /// See [TaskTemplateEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TaskTemplateEntity>(
    _entities[10].properties[6],
  );

  /// See [TaskTemplateEntity.lastUsedAt].
  static final lastUsedAt = obx.QueryDateProperty<TaskTemplateEntity>(
    _entities[10].properties[7],
  );

  /// See [TaskTemplateEntity.seedSlug].
  static final seedSlug = obx.QueryStringProperty<TaskTemplateEntity>(
    _entities[10].properties[8],
  );

  /// See [TaskTemplateEntity.suggestedEstimateMinutes].
  static final suggestedEstimateMinutes =
      obx.QueryIntegerProperty<TaskTemplateEntity>(_entities[10].properties[9]);
}
