meta:
  id: "250130-tasks-interaction-enhancement"
  title: "任务清单交互体验增强迭代蓝图"
  based_on: "documents/spec/tasks/design/250130-task-interactions-enhancement.yaml"
  status: draft
  owner: "AI Assistant"
  created: "2025-01-30"
  version: "1.0"

scope:
  includes:
    - "任务清单页面的滑动操作反馈"
    - "已逾期任务推迟逻辑优化"
    - "跨区域拖拽功能实现"
    - "拖拽限制和错误处理"
    - "种子文件相对天数支持"
    - "SeedTask 模型扩展"
    - "相关测试用例编写"
  excludes:
    - "Inbox 页面的滑动操作（已有实现）"
    - "任务创建和编辑功能"
    - "任务完成和归档的底层逻辑"
    - "用户界面主题和样式调整"

changes:
  code_updates:
    - file: "lib/data/repositories/seed_repository.dart"
      type: modify
      intent: "扩展 SeedTask 模型，添加 dueAt 字段支持相对天数"
    - file: "lib/core/services/seed_import_service.dart"
      type: modify
      intent: "实现相对天数到绝对日期的转换逻辑，支持种子文件中的 dueAt 字段"
    - file: "lib/presentation/widgets/swipe_action_handler.dart"
      type: modify
      intent: "优化已逾期任务的推迟逻辑，确保推迟到今日 23:59:59"
    - file: "lib/presentation/tasks/tasks_drag_target.dart"
      type: modify
      intent: "添加拖拽限制，防止任务拖拽到已逾期区域"
    - file: "lib/core/services/task_service.dart"
      type: modify
      intent: "实现跨区域拖拽的截止时间调整逻辑，设置为目标区域第一天 23:59:59"
    - file: "lib/l10n/app_zh_CN.arb"
      type: modify
      intent: "添加滑动操作和拖拽操作相关的本地化文本"
    - file: "lib/l10n/app_en.arb"
      type: modify
      intent: "添加滑动操作和拖拽操作相关的本地化文本"
    - file: "lib/l10n/app_zh_HK.arb"
      type: modify
      intent: "添加滑动操作和拖拽操作相关的本地化文本"
    - file: "lib/l10n/app_zh.arb"
      type: modify
      intent: "添加滑动操作和拖拽操作相关的本地化文本"
    - file: "assets/seeds/zh_CN/tasks.json"
      type: modify
      intent: "更新种子文件使用相对天数格式，添加已逾期任务测试数据"
    - file: "assets/seeds/en/tasks.json"
      type: modify
      intent: "更新种子文件使用相对天数格式，添加已逾期任务测试数据"
    - file: "assets/seeds/zh_HK/tasks.json"
      type: modify
      intent: "更新种子文件使用相对天数格式，添加已逾期任务测试数据"

  data_model:
    - entity: "SeedTask"
      change: "新增 dueAt 字段，支持 DateTime? 类型，用于存储相对天数或绝对日期"
    - entity: "TaskDraft"
      change: "保持现有 dueAt 字段不变，确保兼容性"
    - entity: "Task"
      change: "保持现有 dueAt 字段不变，确保兼容性"

  tests:
    - type: unit
      focus: "SeedTask 模型 dueAt 字段的序列化和反序列化"
      location: "test/data/repositories/seed_repository_test.dart"
    - type: unit
      focus: "相对天数到绝对日期的转换逻辑"
      location: "test/core/services/seed_import_service_test.dart"
    - type: unit
      focus: "已逾期任务推迟逻辑，验证推迟到今日 23:59:59"
      location: "test/presentation/widgets/swipe_action_handler_test.dart"
    - type: unit
      focus: "跨区域拖拽的截止时间调整逻辑"
      location: "test/core/services/task_service_test.dart"
    - type: unit
      focus: "拖拽限制逻辑，验证不能拖拽到已逾期区域"
      location: "test/presentation/tasks/tasks_drag_target_test.dart"
    - type: widget
      focus: "任务清单页面滑动操作的消息提醒显示"
      location: "test/presentation/tasks/task_list_page_test.dart"
    - type: widget
      focus: "跨区域拖拽的视觉反馈和交互"
      location: "test/presentation/tasks/task_list_page_test.dart"
    - type: integration
      focus: "完整的种子文件导入和任务区域分配流程"
      location: "integration_test/seed_import_test.dart"
    - type: integration
      focus: "任务清单页面的滑动和拖拽操作端到端测试"
      location: "integration_test/task_interactions_test.dart"

  documentation:
    - path: "documents/spec/tasks/design/250130-task-interactions-enhancement.yaml"
      update_type: modify
      reason: "根据实现过程中的发现更新设计细节"
    - path: "documents/architecture/services/seed_import_service.yaml"
      update_type: create
      reason: "记录种子文件相对天数解析的架构设计"
    - path: "documents/architecture/widgets/swipe_action_handler.yaml"
      update_type: modify
      reason: "更新滑动操作处理器的架构文档，包含已逾期任务处理逻辑"

risks:
  - name: "种子文件格式变更可能影响现有数据"
    mitigation: "保持向后兼容，支持旧的绝对日期格式，同时支持新的相对天数格式"
  - name: "拖拽功能与现有排序功能可能冲突"
    mitigation: "仔细测试拖拽和排序的交互，确保不会相互干扰"
  - name: "SnackBar 在 Dismissible 组件中的显示可能不稳定"
    mitigation: "使用 SchedulerBinding.instance.addPostFrameCallback 确保在正确的时机显示"
  - name: "跨区域拖拽的性能影响"
    mitigation: "优化拖拽处理逻辑，避免频繁的数据库操作"
  - name: "相对天数计算可能受时区影响"
    mitigation: "使用本地时区进行计算，确保在不同时区下的一致性"

verification:
  checklist:
    - "运行 flutter test 确保所有单元测试通过"
    - "运行 flutter test integration_test 确保集成测试通过"
    - "运行 flutter analyze 确保代码质量检查通过"
    - "测试种子文件导入，验证相对天数解析正确"
    - "测试已逾期任务的推迟功能，验证推迟到今日 23:59:59"
    - "测试跨区域拖拽，验证截止时间正确调整"
    - "测试拖拽限制，验证不能拖拽到已逾期区域"
    - "测试滑动操作的消息提醒，验证 SnackBar 正确显示"
    - "在不同设备上测试拖拽和滑动的交互体验"
    - "验证本地化文本在所有支持的语言中正确显示"

implementation_phases:
  phase_1_seed_support:
    title: "种子文件相对天数支持"
    tasks:
      - "扩展 SeedTask 模型添加 dueAt 字段"
      - "实现相对天数到绝对日期的转换逻辑"
      - "更新种子文件使用相对天数格式"
      - "编写相关单元测试"
    estimated_effort: "2-3 小时"

  phase_2_swipe_feedback:
    title: "滑动操作消息提醒"
    tasks:
      - "优化 SwipeActionHandler 的消息显示逻辑"
      - "确保 SnackBar 在 Dismissible 组件中正确显示"
      - "添加本地化文本支持"
      - "编写相关测试用例"
    estimated_effort: "2-3 小时"

  phase_3_overdue_logic:
    title: "已逾期任务推迟逻辑优化"
    tasks:
      - "修改推迟逻辑，已逾期任务推迟到今日 23:59:59"
      - "更新相关测试用例"
      - "验证逻辑正确性"
    estimated_effort: "1-2 小时"

  phase_4_drag_enhancement:
    title: "跨区域拖拽功能实现"
    tasks:
      - "实现跨区域拖拽的截止时间调整逻辑"
      - "添加拖拽限制，防止拖拽到已逾期区域"
      - "优化拖拽的视觉反馈"
      - "编写相关测试用例"
    estimated_effort: "3-4 小时"

  phase_5_testing_integration:
    title: "测试和集成验证"
    tasks:
      - "运行完整的测试套件"
      - "进行端到端测试"
      - "性能测试和优化"
      - "文档更新"
    estimated_effort: "2-3 小时"

total_estimated_effort: "10-15 小时"

dependencies:
  - "现有的 SwipeActionHandler 组件架构"
  - "任务服务的拖拽处理方法"
  - "本地化文本资源管理"
  - "现有的拖拽目标组件"
  - "Flutter 测试框架和工具"

rollback_strategy:
  - "保留原始种子文件格式的兼容性"
  - "通过特性开关控制新功能的启用"
  - "准备回滚到原始滑动操作逻辑的代码分支"
  - "维护原始拖拽功能的备份实现"
