meta:
  id: "251201-tasks-inline-edit"
  title: "任务列表内联编辑优化 - 迭代蓝图"
  based_on: "documents/spec/tasks/design/251201-task-list-inline-edit.yaml"
  status: draft
  owner: "AI Assistant"
  created: "2025-12-01"

scope:
  includes:
    - "创建内联可编辑标签组件（InlineEditableTag）"
    - "创建标签添加按钮组件（TagAddButton）"
    - "创建分组标签菜单组件（TagGroupedMenu）"
    - "创建内联截止日期编辑器（InlineDeadlineEditor）"
    - "重构 _TaskLeafTile 为三行布局（标题/标签/截止日期）"
    - "重构 _TaskHeaderRow 集成内联编辑组件"
    - "保留子任务的展开/收起功能"
    - "添加国际化支持（中文、英文）"
    - "编写完整的 widget 测试"
    - "同步应用到收藏夹（Inbox）页面"
  
  excludes:
    - "不修改任务详情页（保留现有详情编辑功能）"
    - "不实现批量编辑功能（留待后续迭代）"
    - "不修改项目卡片的设计（ProjectCard 保持不变）"
    - "不修改轻量任务区域（QuickTasks 已在上一个迭代优化）"

changes:
  code_updates:
    - file: "lib/presentation/widgets/inline_editable_tag.dart"
      type: create
      intent: "创建可删除的标签组件，带 × 图标，支持点击删除"
      details:
        - "基于 ModernTag 组件扩展"
        - "右侧添加 × 图标（CloseButton 或自定义 Icon）"
        - "悬停时 × 图标高亮"
        - "点击 × 触发 onRemove 回调"
        - "删除时有 200ms fade out 动画"
        - "集成 Semantics 标签"
    
    - file: "lib/presentation/widgets/tag_add_button.dart"
      type: create
      intent: "创建添加标签按钮，打开分组菜单选择标签"
      details:
        - "虚线边框按钮，显示 '+ 标签 ▼'"
        - "点击打开 PopupMenuButton（桌面）或 showModalBottomSheet（移动）"
        - "传入未选择的标签组列表"
        - "选择标签后触发 onTagSelected 回调"
        - "只在有未选择的标签组时显示"
    
    - file: "lib/presentation/widgets/tag_grouped_menu.dart"
      type: create
      intent: "创建按标签组分组的菜单，支持同组互斥选择"
      details:
        - "接收 availableTagGroups 参数（未选择的标签组）"
        - "按组显示标签，带分组标题"
        - "分组标题：灰色小字，不可点击"
        - "标签项：ListTile，单选样式"
        - "选中标签后：触发 onTagSelected，关闭菜单"
        - "处理同组互斥逻辑"
    
    - file: "lib/presentation/widgets/inline_deadline_editor.dart"
      type: create
      intent: "创建可点击编辑的截止日期显示组件"
      details:
        - "图标 📅 + 格式化时间文本"
        - "相对时间显示：'今天'、'明天'、'本周五'"
        - "绝对时间显示：'12月1日 15:00'"
        - "过期时：红色背景 + '⚠ 已逾期'"
        - "临近时（24小时内）：橙色背景 + '⏰ 即将到期'"
        - "无截止日期：显示 [+ 设置截止日期] 按钮"
        - "点击打开 showDateTimePicker"
        - "支持清除截止日期功能"
        - "调用 onDeadlineChanged 回调"
    
    - file: "lib/presentation/tasks/task_list_page.dart"
      type: modify
      intent: "重构 _TaskLeafTile 和 _TaskHeaderRow，集成内联编辑组件"
      details:
        - "移除 _TaskLeafTile 的 ExpansionTile（任务本身不再展开）"
        - "改为三行平铺布局："
        - "  第一行：Checkbox + 执行方式图标 + 标题"
        - "  第二行：InlineEditableTag 列表 + TagAddButton"
        - "  第三行：InlineDeadlineEditor"
        - "  第四行（可选）：子任务列表（保留 ExpansionTile）"
        - "重构 _TaskHeaderRow 为独立的标签和截止日期行"
        - "添加标签删除回调：调用 taskService.removeTag"
        - "添加标签添加回调：调用 taskService.addTag，处理同组互斥"
        - "添加截止日期修改回调：调用 taskService.updateDetails"
        - "更新 _TaskTitle 组件，移除冗余信息"
    
    - file: "lib/presentation/inbox/inbox_page.dart"
      type: modify
      intent: "同步应用内联编辑到收藏夹页面"
      details:
        - "查找收藏夹的任务列表渲染代码"
        - "应用与 task_list_page 相同的三行布局"
        - "复用 InlineEditableTag、TagAddButton、InlineDeadlineEditor 组件"
    
    - file: "lib/l10n/app_zh.arb"
      type: modify
      intent: "添加内联编辑相关的中文国际化字符串"
      details:
        - "添加 6 个新的翻译键"
        - "按字母顺序插入"
    
    - file: "lib/l10n/app_en.arb"
      type: modify
      intent: "添加内联编辑相关的英文国际化字符串"
      details:
        - "添加 6 个新的翻译键"
        - "按字母顺序插入"
  
  data_model:
    - entity: "无"
      change: "不涉及数据模型变更，使用现有 Task 和 Tag 模型"
  
  tests:
    - type: widget
      file: "test/presentation/widgets/inline_editable_tag_test.dart"
      focus: "测试可删除标签的渲染和交互"
      test_cases:
        - "渲染标签名和 × 图标"
        - "点击 × 触发 onRemove 回调"
        - "悬停时 × 图标高亮"
        - "删除动画正常播放"
        - "Semantics 标签存在"
    
    - type: widget
      file: "test/presentation/widgets/tag_add_button_test.dart"
      focus: "测试添加标签按钮的显示和交互"
      test_cases:
        - "按钮正常渲染"
        - "点击打开菜单"
        - "传入空标签组时不显示按钮"
        - "选择标签后触发 onTagSelected"
        - "国际化文本正确"
    
    - type: widget
      file: "test/presentation/widgets/tag_grouped_menu_test.dart"
      focus: "测试分组标签菜单的显示和同组互斥逻辑"
      test_cases:
        - "按组显示标签"
        - "分组标题正确渲染"
        - "选择标签后菜单关闭"
        - "同组标签互斥（选中新标签时旧标签移除）"
        - "只显示未选择的标签组"
    
    - type: widget
      file: "test/presentation/widgets/inline_deadline_editor_test.dart"
      focus: "测试截止日期编辑器的显示和交互"
      test_cases:
        - "无截止日期时显示 [+ 设置截止日期]"
        - "有截止日期时显示格式化时间"
        - "过期时显示红色背景和警告"
        - "临近时显示橙色背景和提示"
        - "点击打开日期选择器"
        - "修改截止日期后触发 onDeadlineChanged"
        - "清除截止日期功能正常"
        - "相对时间格式正确（今天、明天、本周五）"
    
    - type: widget
      file: "test/presentation/tasks/task_list_inline_edit_test.dart"
      focus: "测试任务列表项的整体布局和内联编辑流程"
      test_cases:
        - "三行布局正常渲染"
        - "标签可删除，UI 实时更新"
        - "标签可添加，同组互斥生效"
        - "截止日期可编辑"
        - "子任务展开/收起正常"
        - "国际化文本正确"
  
  documentation:
    - path: "documents/spec/tasks/design/251201-task-list-inline-edit.yaml"
      update_type: reference_only
      note: "设计文档已创建，作为本次迭代的依据"
    
    - path: "documents/spec/tasks/iteration/251201-task-list-inline-edit.yaml"
      update_type: create
      note: "本文档，迭代蓝图"

risks:
  - name: "任务列表 UI 大幅改动，可能影响用户习惯"
    mitigation: "保留核心交互逻辑（Checkbox、展开子任务），只优化元数据编辑；提供清晰的视觉引导"
    affected_files:
      - "lib/presentation/tasks/task_list_page.dart"
      - "lib/presentation/inbox/inbox_page.dart"
  
  - name: "标签同组互斥逻辑复杂，可能出现边界情况"
    mitigation: "编写全面的单元测试，覆盖所有标签组合；参考现有 tag_selector.dart 的逻辑"
  
  - name: "截止日期格式化逻辑可能与本地化冲突"
    mitigation: "使用 intl 包的 DateFormat，支持多语言；测试中英文两种语言"
  
  - name: "移动端和桌面端的菜单展示方式不同"
    mitigation: "使用 Platform.isAndroid/iOS 判断，桌面用 PopupMenu，移动用 BottomSheet"
  
  - name: "性能问题：列表项复杂度增加，可能影响滚动流畅度"
    mitigation: "使用 const 构造函数优化；避免不必要的 rebuild；在长列表中测试性能"
  
  - name: "Inbox 页面的任务列表实现可能与 Tasks 页面不同"
    mitigation: "先查看 Inbox 代码结构；尽量复用组件；必要时重构为统一的任务列表组件"

verification:
  checklist:
    - "✅ 所有新组件文件创建完成"
    - "✅ 所有修改的文件更新完成"
    - "✅ 运行 flutter pub get 确保依赖正常"
    - "✅ 运行 flutter gen-l10n 生成国际化文件"
    - "✅ 运行 flutter analyze 无错误无警告"
    - "✅ 运行 flutter test test/presentation/widgets/inline_editable_tag_test.dart 通过"
    - "✅ 运行 flutter test test/presentation/widgets/tag_add_button_test.dart 通过"
    - "✅ 运行 flutter test test/presentation/widgets/tag_grouped_menu_test.dart 通过"
    - "✅ 运行 flutter test test/presentation/widgets/inline_deadline_editor_test.dart 通过"
    - "✅ 运行 flutter test test/presentation/tasks/task_list_inline_edit_test.dart 通过"
    - "✅ 运行 flutter test 全量测试通过"
    - "✅ 手动测试 Tasks 页面的内联编辑功能"
    - "✅ 手动测试 Inbox 页面的内联编辑功能"
    - "✅ 测试标签删除功能"
    - "✅ 测试标签添加功能和同组互斥"
    - "✅ 测试截止日期编辑和清除"
    - "✅ 测试相对时间格式（今天、明天、本周五）"
    - "✅ 测试过期和临近提示"
    - "✅ 测试子任务展开/收起"
    - "✅ 测试深色模式"
    - "✅ 测试中英文国际化"
    - "✅ 测试移动端和桌面端菜单显示"

implementation_order:
  phase1_foundation:
    - step: 1
      task: "创建 InlineEditableTag 组件"
      reason: "最基础的组件，其他组件可能依赖它"
      files:
        - "lib/presentation/widgets/inline_editable_tag.dart"
        - "test/presentation/widgets/inline_editable_tag_test.dart"
    
    - step: 2
      task: "创建 TagGroupedMenu 组件"
      reason: "TagAddButton 需要使用这个菜单"
      files:
        - "lib/presentation/widgets/tag_grouped_menu.dart"
        - "test/presentation/widgets/tag_grouped_menu_test.dart"
    
    - step: 3
      task: "创建 TagAddButton 组件"
      reason: "依赖 TagGroupedMenu"
      files:
        - "lib/presentation/widgets/tag_add_button.dart"
        - "test/presentation/widgets/tag_add_button_test.dart"
    
    - step: 4
      task: "创建 InlineDeadlineEditor 组件"
      reason: "独立组件，不依赖其他新组件"
      files:
        - "lib/presentation/widgets/inline_deadline_editor.dart"
        - "test/presentation/widgets/inline_deadline_editor_test.dart"
  
  phase2_integration:
    - step: 5
      task: "添加国际化字符串"
      reason: "后续集成时需要用到"
      files:
        - "lib/l10n/app_zh.arb"
        - "lib/l10n/app_en.arb"
    
    - step: 6
      task: "重构 _TaskLeafTile 和 _TaskHeaderRow"
      reason: "集成所有新组件到任务列表"
      files:
        - "lib/presentation/tasks/task_list_page.dart"
    
    - step: 7
      task: "同步更新 Inbox 页面"
      reason: "保持收藏夹和任务列表的一致性"
      files:
        - "lib/presentation/inbox/inbox_page.dart"
  
  phase3_testing:
    - step: 8
      task: "编写集成测试"
      reason: "测试整体流程"
      files:
        - "test/presentation/tasks/task_list_inline_edit_test.dart"
    
    - step: 9
      task: "运行全量测试和手动测试"
      reason: "确保所有功能正常"
    
    - step: 10
      task: "修复发现的问题"
      reason: "根据测试结果调整"

estimated_effort:
  total_hours: 12-16
  breakdown:
    - task: "创建 4 个新组件及测试"
      hours: 6-8
    - task: "重构任务列表和收藏夹"
      hours: 4-6
    - task: "国际化和样式调整"
      hours: 1-2
    - task: "测试和 bug 修复"
      hours: 1-2

acceptance_criteria:
  functional:
    - "用户可以在任务列表中点击 × 删除标签"
    - "用户可以在任务列表中点击 [+ 标签 ▼] 添加标签"
    - "标签菜单按组显示，只显示未选择的标签组"
    - "选择同组标签时，自动移除旧标签"
    - "用户可以点击截止日期编辑时间"
    - "用户可以点击 [+ 设置截止日期] 添加截止日期"
    - "过期任务显示红色警告"
    - "临近任务（24小时内）显示橙色提示"
    - "相对时间正确显示（今天、明天、本周五）"
    - "子任务展开/收起功能正常"
    - "所有操作立即生效，无需保存按钮"
  
  non_functional:
    - "所有操作响应时间 < 200ms"
    - "动画流畅，60fps"
    - "支持深色模式"
    - "支持中英文国际化"
    - "支持屏幕阅读器"
    - "所有点击区域 ≥ 44x44 px（移动端）"
    - "flutter analyze 无错误无警告"
    - "flutter test 全部通过"
    - "代码覆盖率 ≥ 80%"

rollback_plan:
  trigger_conditions:
    - "发现严重 bug 导致任务列表无法正常使用"
    - "性能问题导致列表滚动卡顿"
    - "用户反馈操作逻辑混乱"
  
  rollback_steps:
    - step: 1
      action: "通过 git revert 回滚所有相关 commit"
    - step: 2
      action: "运行 flutter test 确保回滚后测试通过"
    - step: 3
      action: "通知用户和团队"
    - step: 4
      action: "分析问题，制定修复计划"
  
  prevention:
    - "分阶段发布：先在内部测试环境验证"
    - "保留旧代码的 feature flag，可快速切换回旧版本"
    - "充分的测试覆盖"

post_implementation:
  follow_up_tasks:
    - "收集用户反馈，评估内联编辑的使用频率"
    - "监控性能指标，确保列表滚动流畅"
    - "考虑添加批量编辑功能（选中多个任务，统一修改标签）"
    - "考虑添加快捷键支持（如 Cmd+T 添加标签）"
    - "考虑添加标签颜色自定义"
  
  metrics_to_track:
    - "标签删除操作频率"
    - "标签添加操作频率"
    - "截止日期编辑操作频率"
    - "用户从列表到详情页的跳转频率（应该减少）"
    - "任务编辑总耗时（应该减少）"
